### PR TITLE
Update the plot range to be from 2015 and add safe mode line

### PR DESCRIPTION
**Pull request by jeanconn**
Update the plot range to be from 2015 and add recent safe mode lines.

### Functional Testing:
On head ska3 ran
```
python vv_trend.py
```
hist2d_fig
hist2d_fig_n100
mag_vs_resid

### CODE REVIEW

**Comment by jeanconn** [comment]
This is basically all still a mess (needs cleanup and packaging) but this would at least help the plot be what we want.
Works fine in ska3.

**Comment by taldcroft** [comment]
Add a `Functional testing` section to the Description and document what you did to test and include an example output image.

**Comment by taldcroft** [comment]
Also, does the "runs fine in ska3" apply to 2023.1 now?

**Comment by jeanconn** [comment]
OK, I'll stop trying to get away with less documented testing on trending PRs (I've overall felt that the impact for any mistake was minimal to the point where installing the code and seeing what happens was not unreasonable).  Last run done with flight ska3 so yes, fine on ska3-prime.  Should be packaged up at some point, but could run out of flight ska3 now.

I don't have an explanation for the improved V&V rms *before* the safe mode.

**Review by taldcroft — APPROVED** [review]
Looks great!

**Comment by taldcroft** [comment]
Is that recent jump up at the time of the Oct-2022 safe mode? That might make sense.

**Comment by jeanconn** [comment]
Great point about the previous safe mode Tom.  I've added another line and changed the scales a bit more.  Plots updated in the description.

**Comment by jeanconn** [comment]
I re-requested review just so I'd be sure @taldcroft didn't have new questions or suggestions after the tiny plot changes after the previous review.

**Review by taldcroft — APPROVED** [review]
Looks great!

**Pull request merged**
